# 抛出和捕获异常



异常分类：

#### Throwable：所有错误的祖先

#### Exception类错误：

**Exception类是所有异常的父类**

​		Checked Exception（非RuntimeException的Exception子类），程序员	必须处理，以发生后处理为主（改bug）。编译器会辅助检查。



​		Unchecked Exception中的RuntimeException子类，程序必须处理，以预防为主。编译器不关心此类异常，也不会辅助检查。



#### Error的子类，可以不用处理，Error是更严重的问题，一般是系统层面的

**使用try和catch关键字可以捕获和抛出异常：**

try：正常业务逻辑代码

catch：当try发生异常，将执行catch代码。若无异常，绕开继续执行程序，java允许多个catch存在，但是只会异常最多只会匹配一个catch

finally：当try或者catch执行结束后，必须要执行finally

finally一般用于收尾工作

```java
public class Main {
    public static void main(String[] args) {
    try {
        int a=2/0;//有异常，跳到下一个catch
        System.out.println("a is "+a);
    }catch (ArithmeticException error){//catch异常匹配成功，进入catch
        int a = 2/0;
        System.out.println("erroe!");
        error.printStackTrace();
    }catch (Throwable err){//因为上个catch已经匹配异常，因此这个catch不会执行
        System.out.println("ok");
    }
    finally {//无论如何，最后都一定会执行finally
        System.out.println("over");
    }
    }
}
//执行结果：over
```

**在catch中小异常写在前面，大异常写在后面**

方法存在可能异常的语句，但不处理，可以用throws来声明异常（扔掉bug）

调用带有throws异常的方法，要么处理这些异常，或者再次向外throws，直到main函数为止。



解决throw异常也需要用try-catch-finally来解决

```java
public class Throw {
    public int divide(int x,int y)throws ArithmeticException{//抛出了可能存在的异常，交给调用的客户类去处理，如果客户类不处理则需要再次抛出直到main函数里面
        int result = x/y;
        return x/y;
    }
}


  Throw a = new Throw();
        try {
            System.out.println(a.divide(2, 0));使用try-catch-finally来解决异常
            System.out.println("ok");
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("ok");
        }finally {
            System.out.println("ok!!!!!!");
        }
    }
```





**注：1.一个方法被覆盖，覆盖它的方法必须抛出相同的异常或者异常的子类**

​		**2.如果父类的方法抛出多个异常，那么重写的子类方法必须抛出异常的子集，也就是不能抛出新的异常**即子类的异常范围不能大于父类异常

例子；

```java
public class kid extends Throw {
    public int divide(int x,int y)throws Exception(或者ArithmeticException){
        //这里只能选择抛出与父类异常相同或者属于父类异常的子类异常的异常，或者选择不抛出异常
        System.out.println("ok?!");
        return x/y;
    }
}
```



**自定义异常：**

自定义异常需要继承Exception类或其子类。

-继承自Exception，就变成Checked Exception

-继承自RuntimeException，就变成Unchecked Exception

**自定义重点在于构造函数**



```java
public class kid extends Exception{//自定义异常，继承父类Exception的异常
    private String returnCode;//异常对应的返回码
    private String returnMsg;//异常对应描述信息
    public kid(){
         super();//无参构造
    }
    public kid(String returnMsg)//只有Msg的构造
    {
        super(returnMsg);
        this.returnMsg=returnMsg;
    }
    public kid(String returnMsg,String returnCode){//含参构造
        super();
        this.returnMsg=returnMsg;
        this.returnCode=returnCode;
    }
    public String getReturnCode(){
    return returnCode;
    }
    public String getReturnMsg(){
        return returnMsg;
    }
}
public class Throw {//抛出异常的类
    public static void test() throws kid {//throws是异常声明
        throw new kid("14250", "异常！nmsl!");//throw是主动抛出异常
    }
}
public class Main {

    public static void main(String[] args) throws kid {
        Throw t = new Throw();
        try {//解决抛出的自定义异常
            t.test();
        }catch (kid a){
            a.printStackTrace();
            System.out.println("returnCode"+a.getReturnCode());
            System.out.println("returnMsg"+a.getReturnMsg());
        }
    }
}

结果：kid//异常名
	at Throw.test(Throw.java:3)//第一个异常抛出所在位置
	at Main.main(Main.java:6)//第二个异常抛出所在位置，若有其它客户类调用自定义异常，则会一直抛出，直到main函数
	returnCode异常！nmsl!
	returnMsg14250
```

异常类：

 1.**Throwable---所有异常类的父类**

Throwable常用方法：1.getMessage（）：返回String类型的异常信息

​									2.printStackTrace（）：打印跟踪方法调用栈而获得详细异常信息。在程序调试阶段，此方									法可以用于跟踪错误         

2. **Throwable的直接子类-----Error类**

   表示单靠程序本身无法恢复的严重错误，比如内存空间不足或Java虚拟机的方法调用栈溢出。在大多数情况下，遇到这样的错误时，建议将程序终止

3. **Exception类**：表示程序本身可以处理的异常程序，当程序出现此类异常时，应该尽可能去解决

4. Exception的子类：

   | IOException类：                 | 操作输入流和输出流时可能出现的异常                           | 备注                                                         |
   | ------------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
   | **ArithmeticException类**       | **数学异常，比如把整数除以0，就会出现这种异常**              |                                                              |
   | **NullPointerException类**      | **空指针异常**。**当引用变量为**null时，**试图访问对象的属性或方法**，**就会出现这种异常** |                                                              |
   | **IndexOutOfBoundsException类** | **下标越界异常，它的子类ArrayIndexOutOfBoundsException**表示数组索引越界异常 |                                                              |
   | **ClassCastException类**        | 类型转换异常，（多态问题）                                   |                                                              |
   | **IllegalArgumentException类**  | 非法参数异常，用来检查方法中的参数是否合法                   |                                                              |
   | **RuntimeException类**          | 运行时异常，包括它的子类（EOFException和FileNotFoundException），**注意这类异常编译器不会检查它，因此在出现这类异常时，程序往往会异常终止** | 除**RuntimeException类**及其子类外，其它的Exception类及其子类都属于受检查异常，受检查异常都会被Java编译器自动检测 |

   ### 小结：

   与异常有关的关键字用途：

   1.try-catch语句：捕获异常

   2.finally语句：任何情况下都必须执行的语句

   3.throws子句：声明任何方法可能会出现的异常

   4.throw语句：抛出异常

   5.语法规则：

   （1）try代码块后面至少有一个catch代码块或者finally代码块。

   （2）try代码块后面有多个catch，Java虚拟机会把实际抛出的异常对象依次和各个catch代码块声明的异常类型匹配，**有且只能匹配一个catch语句并执行这个catch代码块里的程序**。

   （3）try代码块后面可以有0个或多个catch代码块，还可以有0个或多个finally代码块。

   6.运行时异常（RuntimeException及其子类异常）：这种异常的特点是Java编译器不会检查它，即使程序中出现这类异常时，**即使没有try-catch语句也会编译通过**

   7.**受检查异常：**除了RuntimeException及其子类异常以外，其它的Expection类及其子类都属于受检查异常。如果出现这类异常，必须用try-catch语句和throw语句处理，不然可能会编译错误。